# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'support-im-ios-debugdemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for support-im-ios-debugdemo

# RongCloud SDK
#  IM SDK
#  pod 'RongCloudIM_Private', '5.6.2.50'

#  音视频 SDK
#  pod 'RongCloudRTC_Private', '5.6.2.50'

# Other
  pod 'IQKeyboardManager'
  pod 'SVProgressHUD'
  pod 'SDWebImage', '5.11.1'
  pod 'AFNetworking'
  pod 'Masonry', '1.1.0'
  
end
